services:
  database:
    image: postgres:latest
    ports:
      - "5454:5432"
    networks:
      - weather-app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-weather-data:/var/lib/postgresql/data

volumes:
  db-weather-data:

networks:
  weather-app:
    driver: bridge
